# Generated by Django 5.2.7 on 2025-10-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_card_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='color',
            field=models.CharField(default='#007ACF', max_length=7),
        ),
    ]
