# Generated by Django 5.2.7 on 2025-10-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_card_priority'),
    ]

    # Use Python-based conditional DDL for MySQL versions without ADD COLUMN IF NOT EXISTS
    def _add_color_if_missing(apps, schema_editor):
        table = schema_editor.connection.ops.quote_name('product_column')
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f"SHOW COLUMNS FROM {table} LIKE %s", ('color',))
            exists = cursor.fetchone() is not None
            if not exists:
                cursor.execute(
                    f"ALTER TABLE {table} ADD COLUMN `color` varchar(7) NOT NULL DEFAULT '#007ACF'"
                )

    def _drop_color_if_present(apps, schema_editor):
        table = schema_editor.connection.ops.quote_name('product_column')
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f"SHOW COLUMNS FROM {table} LIKE %s", ('color',))
            exists = cursor.fetchone() is not None
            if exists:
                cursor.execute(
                    f"ALTER TABLE {table} DROP COLUMN `color`"
                )

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_add_color_if_missing, _drop_color_if_present),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='column',
                    name='color',
                    field=models.CharField(default='#007ACF', max_length=7),
                ),
            ],
        ),
    ]
