# Generated by Django 5.2.7 on 2025-10-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_card_priority'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE `product_column` "
                        "ADD COLUMN IF NOT EXISTS `color` varchar(7) "
                        "NOT NULL DEFAULT '#007ACF';"
                    ),
                    reverse_sql=(
                        "ALTER TABLE `product_column` "
                        "DROP COLUMN IF EXISTS `color`;"
                    ),
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='column',
                    name='color',
                    field=models.CharField(default='#007ACF', max_length=7),
                ),
            ],
        ),
    ]
