# Generated by Django 5.2.7 on 2025-10-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_remove_user_groups_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='color',
            field=models.CharField(default='#0B97F4', max_length=7),
        ),
    ]
