# Generated by Django 5.2.7 on 2025-10-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_remove_user_groups_remove_user_is_active_and_more'),
    ]

    operations = [
        # This branch also attempted to add the same column. Make it idempotent
        # and avoid state duplication by only performing a conditional DB change.
        migrations.RunSQL(
            sql=(
                "ALTER TABLE `product_column` "
                "ADD COLUMN IF NOT EXISTS `color` varchar(7) "
                "NOT NULL DEFAULT '#0B97F4';"
            ),
            reverse_sql=(
                "ALTER TABLE `product_column` DROP COLUMN IF EXISTS `color`;"
            ),
        ),
    ]
