# Generated by Django 5.2.7 on 2025-10-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_column_color'),
        ('Product', '0007_alter_column_color'),
    ]

    operations = [
    ]
