# Generated by Django 5.2.7 on 2025-10-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_carouselimage_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilepicture',
            field=models.ImageField(default='profilepic/default.png', upload_to='profilepic/'),
        ),
    ]
