# Generated by Django 5.2.7 on 2025-10-16 23:42

import Product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_user_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepicture',
            field=models.ImageField(default='profilepic/default.png', upload_to=Product.models.upload_to_user_profile),
        ),
    ]
