# Generated by Django 5.2.7 on 2025-10-23 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_alter_user_profilepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='Product.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='Product.user')),
            ],
            options={
                'verbose_name': 'Board Membership',
                'verbose_name_plural': 'Board Memberships',
                'indexes': [models.Index(fields=['board', 'user'], name='Product_boa_board_i_deb777_idx')],
                'unique_together': {('board', 'user')},
            },
        ),
    ]
